export const produtos = [
  {
    id: 1,
    marca: 'Berzo',
    nome: 'Jaqueta Puffer Street Jeans',
    categoria: 'jaqueta',
    genero: 'unissex',
    preco: 249.9,
    imagem: '/imagens/produtos/jaqueta-puffer-jeans.png',
  },
  {
    id: 2,
    marca: 'Berzo',
    nome: 'Jaqueta Corta Vento Neon Over',
    categoria: 'jaqueta',
    genero: 'unissex',
    preco: 189.9,
    imagem: '/imagens/produtos/jaqueta-corta-vento-neon.png',
  },
  {
    id: 3,
    marca: 'Berzo',
    nome: 'Jaqueta Black Destroyed Berzo',
    categoria: 'jaqueta',
    genero: 'masculino',
    preco: 219.9,
    imagem: '/imagens/produtos/jaqueta-black-destroyed.png',
  },
  {
    id: 4,
    marca: 'Berzo',
    nome: 'Jaqueta Bomber Satin Cinza',
    categoria: 'jaqueta',
    genero: 'feminino',
    preco: 199.9,
    imagem: '/imagens/produtos/jaqueta-bomber-branca.png',
  },
  {
    id: 5,
    marca: 'Berzo',
    nome: 'Jaqueta Militar ',
    categoria: 'jaqueta',
    genero: 'masculino',
    preco: 239.9,
    imagem: '/imagens/produtos/jaqueta-camuflada-cargo.png',
  },
  {
    id: 6,
    marca: 'Berzo',
    nome: 'Jaqueta Over Branca',
    categoria: 'jaqueta',
    genero: 'feminino',
    preco: 179.9,
    imagem: '/imagens/produtos/jaqueta-over-branca.png',
  },
  {
    id: 7,
    marca: 'Berzo',
    nome: 'Jaqueta Tracksuit Retrô Berzo',
    categoria: 'jaqueta',
    genero: 'unissex',
    preco: 169.9,
    imagem: '/imagens/produtos/jaqueta-tracksuit-retro.png',
  },

  {
    id: 8,
    marca: 'Berzo',
    nome: 'Moletom Oversize Berzo Inverno',
    categoria: 'moletom',
    genero: 'unissex',
    preco: 159.9,
    imagem: '/imagens/produtos/moletom-oversize.png',
  },
  {
    id: 9,
    marca: 'Berzo',
    nome: 'Moletom Canguru Off-Grey Classic',
    categoria: 'moletom',
    genero: 'unissex',
    preco: 149.9,
    imagem: '/imagens/produtos/moletom-canguru-offgrey.png',
  },
  {
    id: 10,
    marca: 'Berzo',
    nome: 'Moletom Crop Hoodie Berzo',
    categoria: 'moletom',
    genero: 'feminino',
    preco: 129.9,
    imagem: '/imagens/produtos/moletom-crop-hoodie.png',
  },
  {
    id: 11,
    marca: 'Berzo',
    nome: 'Moletom Crewneck Grafite Minimalist',
    categoria: 'moletom',
    genero: 'masculino',
    preco: 139.9,
    imagem: '/imagens/produtos/moletom-crewneck-grafite.png',
  },
  {
    id: 12,
    marca: 'Berzo',
    nome: 'Moletom Tie Dye Acid Wash',
    categoria: 'moletom',
    genero: 'unissex',
    preco: 169.9,
    imagem: '/imagens/produtos/moletom-tie-dye-acid.png',
  },
  {
    id: 13,
    marca: 'Berzo',
    nome: 'Moletom Canguru Berzo Logo Vermelho',
    categoria: 'moletom',
    genero: 'masculino',
    preco: 149.9,
    imagem: '/imagens/produtos/moletom-logo-vermelho.png',
  },
  {
    id: 14,
    marca: 'Berzo',
    nome: 'Moletom Lavender Drop Shoulder',
    categoria: 'moletom',
    genero: 'feminino',
    preco: 159.9,
    imagem: '/imagens/produtos/moletom-lavender-drop.png',
  },
  {
    id: 15,
    marca: 'Berzo',
    nome: 'Moletom Sem Capuz Cyberpunk Print',
    categoria: 'moletom',
    genero: 'unissex',
    preco: 145.0,
    imagem: '/imagens/produtos/moletom-cyberpunk.png',
  },
  {
    id: 16,
    marca: 'Berzo',
    nome: 'Moletom Heavyweight Ice Blue',
    categoria: 'moletom',
    genero: 'unissex',
    preco: 179.9,
    imagem: '/imagens/produtos/moletom-ice-blue.png',
  },

  {
    id: 17,
    marca: 'Berzo',
    nome: 'Camiseta Boxy Fit Berzo Amarela',
    categoria: 'camiseta',
    genero: 'unissex',
    preco: 79.9,
    imagem: '/imagens/produtos/camiseta-boxy-amarela.png',
  },
  {
    id: 18,
    marca: 'Berzo',
    nome: 'Camiseta Streetwear Graphic Angel',
    categoria: 'camiseta',
    genero: 'unissex',
    preco: 89.9,
    imagem: '/imagens/produtos/camiseta-graphic-angel.png',
  },
  {
    id: 19,
    marca: 'Berzo',
    nome: 'Camiseta Longline Slim Preta',
    categoria: 'camiseta',
    genero: 'masculino',
    preco: 69.9,
    imagem: '/imagens/produtos/camiseta-longline-preta.png',
  },
  {
    id: 20,
    marca: 'Berzo',
    nome: 'Camiseta Oversize Estampa Cyber',
    categoria: 'camiseta',
    genero: 'unissex',
    preco: 89.9,
    imagem: '/imagens/produtos/camiseta-oversize-cyber.png',
  },
  {
    id: 21,
    marca: 'Berzo',
    nome: 'Camiseta Feminina Crop Gothic',
    categoria: 'camiseta',
    genero: 'feminino',
    preco: 59.9,
    imagem: '/imagens/produtos/camiseta-crop-gothic.png',
  },
  {
    id: 22,
    marca: 'Berzo',
    nome: 'Camiseta Vintage Wash Verde',
    categoria: 'camiseta',
    genero: 'masculino',
    preco: 84.9,
    imagem: '/imagens/produtos/camiseta-vintage-verde.png',
  },
  {
    id: 23,
    marca: 'Berzo',
    nome: 'Camiseta Heavy Metal Font Marinho',
    categoria: 'camiseta',
    genero: 'unissex',
    preco: 79.9,
    imagem: '/imagens/produtos/camiseta-metal-marinho.png',
  },
  {
    id: 24,
    marca: 'Berzo',
    nome: 'Camiseta Minimalist Logo Azul',
    categoria: 'camiseta',
    genero: 'unissex',
    preco: 74.9,
    imagem: '/imagens/produtos/camiseta-minimalist-azul.png',
  },
  {
    id: 25,
    marca: 'Berzo',
    nome: 'Camiseta Overlap Split Duo',
    categoria: 'camiseta',
    genero: 'unissex',
    preco: 92.0,
    imagem: '/imagens/produtos/camiseta-overlap-split.png',
  },
];
